### ISSUE TITLE
Serilog deployed w/ full framework package

### ISSUE THREAD

**Issue by spottedmahn** [mo-esmp/serilog-enrichers-clientinfo#6]
When I install the NuGet package on a full framework project it is including `Serilog.dll (v2.4.0.0)`

![image](https://user-images.githubusercontent.com/14079228/101993982-d44f8000-3c8c-11eb-9303-88bec936b81d.png)

Obviously, this enricher shouldn't be deploying Serilog, just taking a dependency on it as it causes problems like this: [MissingMethodException Serilog.Context.LogContext.Push](https://stackoverflow.com/questions/65268938/missingmethodexception-serilog-context-logcontext-push)

---

Seems to be related: [Including assembly files](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-assembly-files)

```xml
<files>
  <file src="src\Serilog.Enrichers.ClientInfo\bin\$target$\net452\*.dll" target="lib/net452" />
  <file src="src\Serilog.Enrichers.ClientInfo\bin\$target$\netstandard2.0\*.dll" target="lib/netstandard2.0" />
  <file src="src\Serilog.Enrichers.ClientInfo\bin\$target$\netstandard2.1\*.dll" target="lib/netstandard2.1" />
</files>  
```

>If you follow the conventions described in Creating a Package, you do not have to explicitly specify a list of files in the `.nuspec` file. The `nuget pack` command automatically picks up the necessary files.

Was there a reason not to use the automatic behavior?

---

I see it puts `Serilog.dll` in the bin directory on `net452`:

![image](https://user-images.githubusercontent.com/14079228/101993923-51c6c080-3c8c-11eb-9625-c76d437ec87a.png)

I don't see it in the netstandard folders.  I guess msbuild behaves differently? 🤔

**Comment by mo-esmp** [comment]
Sorry for responding late, that is the default behavior of `nuget.exe` for `net452`  for including `Serilog.dll`.

**Comment by spottedmahn** [comment]
>Sorry for responding late

np 😊

>that is the default behavior of `nuget.exe` for `net452`

I was guessing that was the case.  Wonder what's the workaround? 🤔

**Comment by augustoproiete** [comment]
The issue is that [the `nuspec` is telling NuGet to package all the `.dll` files from the output folder](https://github.com/mo-esmp/serilog-enrichers-clientinfo/blob/1811e13259e30c4e610cd2e41b56b0a6c2caf696/Serilog.Enrichers.ClientInfo.nuspec#L31-L33), and for projects targeting .NET Framework, MSBuild copies the dependent dlls to the output folder which causes `Serilog.dll` to be present in `bin\Release\net452`.

The fix is to update the `nuspec` to be specific about including `Serilog.Enrichers.ClientInfo.dll` instead of `*.dll`.

**Comment by spottedmahn** [comment]
awesome 👏, thanks @augustoproiete 🤝
